### ISSUE TITLE
i got an error

### ISSUE THREAD

**Issue by Dano1717** [MrTuxx/SocialPwned#1]
The file can't be accessed

**Comment by MrTuxx** [comment]
Could you be more specific? Which command did you execute? Which file are you referring to?

**Comment by Dano1717** [comment]
python3 socialpwned.py --credentials credentials.json --instagram --info España

**Comment by MrTuxx** [comment]
I just tested it and it works fine. Check it out:
 - That you have created the file in JSON format with the same name as in the command.
 - That the path is correct.
 - That the user has read permissions on the credentials file.
