### ISSUE TITLE
Incorrect JSON format

### ISSUE THREAD

**Issue by aboalwad** [MrTuxx/SocialPwned#2]
Incorrect JSON format
![Screenshot 2020-09-24 14:03:45](https://user-images.githubusercontent.com/71557519/94273787-e1bd5f80-ff12-11ea-8f27-c7583ef8ec9f.png)

**Comment by aboalwad** [comment]
![Uploading Screenshot 2020-09-25 10:28:21.png…]()

**Comment by aboalwad** [comment]
![Screenshot 2020-09-25 10:28:21](https://user-images.githubusercontent.com/71557519/94282149-7cbb3700-ff1d-11ea-89e9-258c8933cebe.png)

**Comment by MrTuxx** [comment]
RTFM
