### ISSUE TITLE
Can´t login to instagram

### ISSUE THREAD

**Issue by x0wm** [MrTuxx/SocialPwned#21]
tried `python3 socialpwned.py --credentials credentials.json --instagram --target-ig kimkardashian --pwndb` and got `[!] Can't Login to Instagram!`, already checked the password in `credentials.json` being correct and instagram not asking for 2FA

**Comment by MrTuxx** [comment]
Hello,

It's already fixed.

It was necessary to update the version of the Instagram application used in the User Agent to make requests.  The docker hub image was also updated.
